version: "3.9"
services:
  web:
    image: nginxdemos/hello
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
    - 8080:80
    environment:
    - NGINX_PORT=80
  prometheus:
    image: prom/prometheus:v2.42.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - 9090:9090
    volumes:
    - /home/federico/prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
    external: true
