groups:
- name: testing
  rules:
  # Alert for any instance that is unreachable for > 1 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "Instance is down"
      description: "The instance has been down for more than 1 minute."

  # Alert for any instance that has a median request latency > 1s.
  - alert: APIHighRequestLatency
    expr: api_http_request_latencies_second{quantile="0.5"} > 1
    for: 1m
    annotations:
      summary: "High request latency on the instance"
      description: "The instance has a median request latency above 1s"

